In [ ]:
import pandas as pd
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from skimage.filters import sobel 
import cv2
from skimage.feature import greycomatrix,greycoprops
import os

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
!pip install unrar


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!unrar  x  gdrive/My\ Drive/DATA-FOR-ML/indic-dev.rar

Streaming output truncated to the last 5000 lines.
Extracting  indic-dev/Odiya/Odiya_478.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_479.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_48.tif                                  50%  OK 
Extracting  indic-dev/Odiya/Odiya_480.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_481.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_482.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_483.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_484.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_485.tif                                 50%  OK 
Extracting  indic-dev/Odiya/Odiya_486.tif                                 50%  OK 
Extracting  indic-dev/Odiya/O

In [ ]:
bengali_text_images = os.listdir("indic-dev/Bengali/")
Devanagiri_text_images = os.listdir("indic-dev/Devanagiri/")
English_text_images = os.listdir("indic-dev/English/")
Gujarathi_text_images = os.listdir("indic-dev/Gujrathi/")
Kannada_text_images = os.listdir("indic-dev/Kannada/")
Malayalam_text_images = os.listdir("indic-dev/Malayalam/")
Odiya_text_images = os.listdir("indic-dev/Odiya/")
Punjabi_text_images = os.listdir("indic-dev/Punjabi/")
Tamil_text_images = os.listdir("indic-dev/Tamil/")
Telugu_text_images = os.listdir("indic-dev/Telugu/")
Urdu_text_images = os.listdir("indic-dev/urdu/")


In [ ]:
languages = os.listdir('indic-dev/')
languages 

['Kannada',
 'Gujrathi',
 'Devanagiri',
 'Telugu',
 'urdu',
 'Tamil',
 'Punjabi',
 'English',
 'Malayalam',
 'Odiya',
 'Bengali']

In [ ]:
SIZE= 32 *2

def data_to_numpy(language,text_images):
    data_images = []
    data_labels = []
   
    path = "indic-dev/{}".format(language)
    label = language
    if path:
        c = 0
        for i in text_images :
            img_path = path + '/'+ i
            c = c+1
            img = cv2.imread(img_path, 0) #Reading color images
            #print(img)
            img = cv2.resize(img, (SIZE, SIZE)) #Resize images
                
            data_images.append(img)
            data_labels.append(label)
            if c== 950:
                break
    # changing to numpy array        

    data_images = np.array(data_images)
    data_labels = np.array(data_labels)

    return (data_images,data_labels)

In [ ]:
Bengali_images,Bengali_labels= data_to_numpy('Bengali',bengali_text_images)
Devanagiri_images,Devanagiri_labels= data_to_numpy('Devanagiri',Devanagiri_text_images)
English_images,English_labels= data_to_numpy('English',English_text_images)
Gujarathi_images,Gujarathi_labels= data_to_numpy('Gujrathi',Gujarathi_text_images)
Kannada_images,Kannada_labels= data_to_numpy('Kannada',Kannada_text_images)
Odiya_images,Odiya_labels= data_to_numpy('Odiya',Odiya_text_images)
Punjabi_images,Punjabi_labels= data_to_numpy('Punjabi',Punjabi_text_images)
Tamil_images,Tamil_labels= data_to_numpy('Tamil',Tamil_text_images)
Telugu_images,Telugu_labels= data_to_numpy('Telugu',Telugu_text_images)
Urdu_images,Urdu_labels= data_to_numpy('urdu',Urdu_text_images)

In [ ]:
English_images.shape

(228, 64, 64)

In [ ]:
data_images = np.concatenate((Bengali_images,Devanagiri_images,English_images,Gujarathi_images,Kannada_images,Odiya_images,Punjabi_images,Tamil_images,Telugu_images,
                              Urdu_images),axis=0  )
data_labels = np.concatenate((Bengali_labels,Devanagiri_labels,English_labels,Gujarathi_labels,Kannada_labels,Odiya_labels,Punjabi_labels,Tamil_labels,Telugu_labels,
                              Urdu_labels),axis=0  )

In [ ]:
X = data_images
y = data_labels

In [ ]:
# Label encoding 
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(y)


In [ ]:
# LANGUAGES ARE ENCODED TO NUMBERS WITH LANGUAGE INDEXS

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=43)

In [ ]:
# NORMALIZING THE PIXELS
# Normalize pixel values to be between 0 and 1
X_train , X_test = X_train / 255.0, X_test / 255.0

In [ ]:
# div the data in test and validation
# test_size is the validation size
X_test,x_val,y_test,y_val= train_test_split(X,y,test_size=.4,random_state=43)

In [ ]:
y_train

array([4, 3, 7, ..., 4, 5, 8])

In [ ]:
y_test

array([2, 3, 4, ..., 4, 5, 8])

In [ ]:
X_train

array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.31764706],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.76862745],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.63137255, 0.94509804, ..., 0.        ,
         0.        , 0.        ],
        [0.64705882, 0.87058824, 0.98039216, ..., 0.        ,
         0.        , 0.        ],
        [1.        , 1.        , 1.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 1.        ,
         1.        , 1.        ],
        [0. 

In [ ]:
len(X_test)

4390

In [ ]:
len(X_train)

5122

# MODEL ACCHITECTURE

In [ ]:
from tensorflow import keras
# CNN MODELING

In [ ]:
def create_model():
  model = keras.Sequential()
  model.add(keras.layers.Conv2D(256, (8,8), activation='relu', input_shape=(256,256,1),name='INPUT-CNN-LAYER' ))
  model.add(keras.layers.MaxPooling2D((2, 2),name='Pooling-layer'))
  model.add(keras.layers.Conv2D(128, (8, 8), activation='relu',name='Conv-layer' ))

  model.add(keras.layers.MaxPooling2D((2, 2),name='2ND-POOLING-LAYER'))
  model.add(keras.layers.Conv2D(64, (3, 3), activation='relu',name='2-CNN-LAYER-LAYER'))
  model.add(keras.layers.MaxPooling2D((2, 2),name='3ND-POOLING-LAYER'))
  model.add(keras.layers.Conv2D(32, (8, 8), activation='relu',name='3-CNN-LAYER-LAYER'))
  model.add(keras.layers.MaxPooling2D((2, 2),name='4TH-POOLING-LAYER'))
  model.add(keras.layers.Conv2D(18, (8, 8), activation='relu',name='4th-CNN-LAYER-LAYER'))
  model.add(keras.layers.Flatten())
  model.add(keras.layers.Dense(25*25,activation='tanh'))
  model.add(keras.layers.Dense(32, activation='tanh'))
  model.add(keras.layers.Dense(10,activation='softmax'))
  return model 

In [ ]:
model = keras.Sequential()
model.add(keras.layers.Conv2D(64, (8,8), activation='relu', input_shape=(64,64,1),name='INPUT-CNN-LAYER' ))
model.add(keras.layers.MaxPooling2D((2, 2),name='Pooling-layer'))
model.add(keras.layers.Conv2D(32, (8, 8), activation='relu',name='Conv-layer' ))

model.add(keras.layers.MaxPooling2D((2, 2),name='2ND-POOLING-LAYER'))
model.add(keras.layers.Conv2D(16, (2, 2), activation='relu',name='2-CNN-LAYER-LAYER'))
#model.add(keras.layers.MaxPooling2D((2, 2),name='3ND-POOLING-LAYER'))
#model.add(keras.layers.Conv2D(32, (8, 8), activation='relu',name='3-CNN-LAYER-LAYER'))
#model.add(keras.layers.MaxPooling2D((2, 2),name='4TH-POOLING-LAYER'))
#model.add(keras.layers.Conv2D(18, (8, 8), activation='relu',name='4th-CNN-LAYER-LAYER'))
model.add(keras.layers.Flatten())
model.add(keras.layers.Dense(25*25,activation='tanh'))
model.add(keras.layers.Dense(32, activation='tanh'))
model.add(keras.layers.Dense(10,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 INPUT-CNN-LAYER (Conv2D)    (None, 57, 57, 64)        4160      
                                                                 
 Pooling-layer (MaxPooling2D  (None, 28, 28, 64)       0         
 )                                                               
                                                                 
 Conv-layer (Conv2D)         (None, 21, 21, 32)        131104    
                                                                 
 2ND-POOLING-LAYER (MaxPooli  (None, 10, 10, 32)       0         
 ng2D)                                                           
                                                                 
 2-CNN-LAYER-LAYER (Conv2D)  (None, 9, 9, 16)          2064      
                                                                 
 flatten (Flatten)           (None, 1296)              0

In [ ]:
model.compile(optimizer='adam',loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True), metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, epochs=24, 
                    validation_data=(X_test, y_test))

Epoch 1/24


/usr/local/lib/python3.7/dist-packages/tensorflow/python/util/dispatch.py:1082: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  return dispatch_target(*args, **kwargs)


161/161 [==============================] - 16s 12ms/step - loss: 1.4206 - accuracy: 0.5303 - val_loss: 0.9462 - val_accuracy: 0.7091
Epoch 2/24
161/161 [==============================] - 2s 11ms/step - loss: 0.6761 - accuracy: 0.7864 - val_loss: 0.7577 - val_accuracy: 0.7565
Epoch 3/24
161/161 [==============================] - 2s 10ms/step - loss: 0.4734 - accuracy: 0.8481 - val_loss: 0.4939 - val_accuracy: 0.8319
Epoch 4/24
161/161 [==============================] - 2s 11ms/step - loss: 0.3593 - accuracy: 0.8893 - val_loss: 0.3764 - val_accuracy: 0.8756
Epoch 5/24
161/161 [==============================] - 2s 10ms/step - loss: 0.2673 - accuracy: 0.9133 - val_loss: 0.2268 - val_accuracy: 0.9303
Epoch 6/24
161/161 [==============================] - 2s 11ms/step - loss: 0.1757 - accuracy: 0.9490 - val_loss: 0.2820 - val_accuracy: 0.9021
Epoch 7/24
161/161 [==============================] - 2s 10ms/step - loss: 0.1406 - accuracy: 0.9598 - val_loss: 0.2166 - val_accuracy: 0.9244
Epoch 8/2

In [ ]:
# will scale data after modeling
#Epoch 24/25
#161/161 [==============================] - 154s 956ms/step - loss: 0.1198 - accuracy: 0.9590 - val_loss: 0.1436 - val_accuracy: 0.9528

In [ ]:
acc = history.history['accuracy']
print(acc)

NameError: ignored

In [ ]:
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(test_acc)

In [ ]:
# SAVING THE MODEL

In [ ]:
model.save("indic_script_detection_model.h5")  # we can save the model and reload it at anytime in the future
new_model = tf.keras.models.load_model('indic_script_detection_model.h5')

In [ ]:
indic_script_detection = create_model()

# saving the model weight


@evalitate the model 

In [ ]:
import tensorflow as tf 
from tensorflow import keras 
from tensorflow.keras import layers

In [ ]:
X_train[1].shape

# ANN APPROCH with glsm

In [ ]:
model = keras.Sequential([
      keras.layers.LSTM(units=25*25,return_sequences=True,input_shape=(25,1)),
      keras.layers.LSTM(units=25*25*25,return_sequences=True),
      #keras.layers.Flatten(),
      #keras.layers.Conv2D(25*25,activation='tahn',kernel_),
      #keras.layers.Conv2D(25*25*25,activation='relu'),
      #tf.keras.layers.ConvLSTM1D(),
      #keras.layers.Dense(125,activation='tanh'),
      #tf.keras.layers.Dropout(
      #    0.1
      #),
      keras.layers.Dense(25*25*25,activation='tanh'),
      #keras.layers.Dense(25*25*25,activation='tanh'),
      #keras.layers.Flatten(),
      #tf.keras.layers.Dropout(
      #    0.1
      #), 
    
      #keras.layers.Dense(25*25*25,activation='tanh'),
      #tf.keras.layers.Dropout(
      #    0.1
      #),
      keras.layers.Dense(25*25,activation='tanh'),
      keras.layers.Dense(10,activation='softmax')
      
])

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics = ['accuracy']
              )

In [ ]:
tf.config.run_functions_eagerly(True)

In [ ]:
model.fit(X_train,y_train,epochs=100)

In [ ]:
from keras.layers import Dense, Dropout, Embedding, LSTM, Bidirectional

In [ ]:
# USE LSTM

In [ ]:
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape = (X_train.shape[1], X_train.shape[2])))

model.add(Dropout(0.1)) 
model.add(LSTM(units=150))

model.add(Dense(2))

model.compile(loss='mean_squared_error', optimizer='adam', metrics=['mean_absolute_error'])

model.summary()

In [ ]:
# THE BEST ACCURACY THE WE GET FROM BASE NEURAL NET  is : 0.5150
# we will now further change the neural net structure and do hyperperametertuning

In [ ]:
scores = model.evaluate(X_test, y_test)

In [ ]:
scores